apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bitbucket.fullname" . }}
  labels:
{{ include "bitbucket.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bitbucket.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "bitbucket.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 7990
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
              livenessProbe:
                httpGet:
                  path: /status
                  port: 7990
                initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
                periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
                timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
                successThreshold: {{ .Values.livenessProbe.successThreshold }}
                failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
              {{- end }}
              {{- if .Values.readinessProbe.enabled }}
              readinessProbe:
                httpGet:
                  path: /status
                  port: 7990
                initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
                periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
                timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
                successThreshold: {{ .Values.readinessProbe.successThreshold }}
                failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
              {{- end }}
          volumeMounts:
            - name: {{ template "bitbucket.fullname" . }}-bitbucket-volume
              mountPath: "/var/atlassian/application-data/bitbucket"
      volumes:
        - name: {{ template "bitbucket.fullname" . }}-bitbucket-volume
          persistentVolumeClaim:
            claimName: {{ template "bitbucket.fullname" . }}-bitbucket
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
