apiVersion: v1
kind: Service
metadata:
  name: {{ include "bitbucket.fullname" . }}
  labels:
{{ include "bitbucket.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 7990
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "bitbucket.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
